### ISSUE TITLE
dirty package after loading

### ISSUE THREAD

**Issue by vonbecmann** [pharo-project/pharo-llvmDisassembler#3]
Integer has this extensions
aarch64Disassembled
disassembleWith:

but VMMaker-Tools has the same extensions. it's like a collision. 
when  you discard all and load this package then you get VMMaker-Tools dirty. and when you do it with VMMaker-Tools, then this package is dirty. you cannot get a clean loaded package. it is circular.

**Comment by guillep** [comment]
Yes, I saw this too, I think it's fixed in the latest dev branch, we will fix it soon :)

**Comment by guillep** [comment]
I can confirm it's fixed in the latest dev branch of the VM!
