### ISSUE TITLE
Broken test when llvm-config not working

### ISSUE THREAD

**Issue by guillep** [pharo-project/pharo-llvmDisassembler#9]
I don't have llvm-config working correctly on my machine, so it returns an empty string for  `llvm-config --libdir`.

<img width="629" alt="imagen" src="https://user-images.githubusercontent.com/708322/212018442-2bc33231-c1c2-41e0-9071-df6a162c1160.png">

This makes `testKnownMacPaths` fail.
However, my system finds llvm somewhere else, so everything else seems alright.
I wonder if this failing assertion is really needed.

<img width="537" alt="imagen" src="https://user-images.githubusercontent.com/708322/212018813-9f11a835-796b-4316-8cf2-2aa4b5ce94e0.png">

**Comment by hernanmd** [comment]
Maybe none of the answered paths should be allowed to be empty?
I don't know if it's safer to make the test fail because otherwise the problem remain undetected until very late.

On the other hand the test assumes llvm-config is installed and working properly.
